# Generated by Django 5.2.8 on 2025-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
